### ISSUE TITLE
Dimension Error

### ISSUE THREAD

**Issue by vndee** [AyushExel/GANs#1]
Hi,
I've tried to run your code in Google Colab. But I've got an error:

https://colab.research.google.com/drive/1qjVKq1LRtkcfn7P_hauoN88zKDeNF7OY

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-29-b1f5df28f13c> in <module>()
      2 
      3 for epoch in tqdm_notebook(range(EPOCHS), desc = 'Trainning'):
----> 4     for i, (imgs, _) in enumerate(dataset):
      5 
      6         # grouth truths

/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py in __next__(self)
    613         if self.num_workers == 0:  # same-process loading
    614             indices = next(self.sample_iter)  # may raise StopIteration
--> 615             batch = self.collate_fn([self.dataset[i] for i in indices])
    616             if self.pin_memory:
    617                 batch = pin_memory_batch(batch)

/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py in <listcomp>(.0)
    613         if self.num_workers == 0:  # same-process loading
    614             indices = next(self.sample_iter)  # may raise StopIteration
--> 615             batch = self.collate_fn([self.dataset[i] for i in indices])
    616             if self.pin_memory:
    617                 batch = pin_memory_batch(batch)

/usr/local/lib/python3.6/dist-packages/torchvision/datasets/mnist.py in __getitem__(self, index)
     93 
     94         if self.transform is not None:
---> 95             img = self.transform(img)
     96 
     97         if self.target_transform is not None:

/usr/local/lib/python3.6/dist-packages/torchvision/transforms/transforms.py in __call__(self, img)
     58     def __call__(self, img):
     59         for t in self.transforms:
---> 60             img = t(img)
     61         return img
     62 

/usr/local/lib/python3.6/dist-packages/torchvision/transforms/transforms.py in __call__(self, tensor)
    161             Tensor: Normalized Tensor image.
    162         """
--> 163         return F.normalize(tensor, self.mean, self.std, self.inplace)
    164 
    165     def __repr__(self):

/usr/local/lib/python3.6/dist-packages/torchvision/transforms/functional.py in normalize(tensor, mean, std, inplace)
    206     mean = torch.tensor(mean, dtype=torch.float32)
    207     std = torch.tensor(std, dtype=torch.float32)
--> 208     tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
    209     return tensor
    210 

RuntimeError: output with shape [1, 28, 28] doesn't match the broadcast shape [3, 28, 28]

Can you help me to fix it. Thanks.

**Comment by AyushExel** [comment]
@vndee Thanks for bringing it to my attention. I just had a look on the code and on running it on colab, I'm getting the same error. But the strange part is that the same code is executing without any errors on my system. Maybe it is an issue of colab. Have you tried to run this code directly on your system ? Please try that and let me know if the same error persists.

**Comment by richaagrawa** [comment]
Hello, @vndee have you solved the issue on this code, as I am also getting the same problem, similar errors while running the program on google colab, and while running this code on the system it is taking a lot of time.

**Comment by nitinsatpute** [comment]
Downgrade torchvision. Run following if the error is in the system: I did not explore the colab.
pip install torchvision==0.2.1
